### ISSUE TITLE
Custom Data Type for Backend Response

### ISSUE THREAD

**Issue by JonathanLorimer** [Benjmhart/haskql#2]
this will give our frontend access to the data it requires rather than having to handle raw JSON

**Comment by Benjmhart** [comment]
backend response has 2 shapes:

1. {"Global Quote":{}} - invalid symbol
2. {"Global Quote": {"07. latest trading day":"2019-03-08","03. high":"110.7100","08. previous close":"110.3900","01. symbol":"MSFT","10. change percent":"0.1087%","06. volume":"22818430","02. open":"109.1600","05. price":"110.5100","04. low":"108.8100","09. change":"0.1200"}}

I feel like we should be able to parse that to a Maybe GlobalQuote

**Comment by Benjmhart** [comment]
So I've got this parsing into  a maybe quote with some helper functions,  I've put the type synonyms and helpers into a model file, Model.Quote.

we should add newType wrappers but I need to spend time better understanding the PS type system.

I've also got this rendering out.   Making separate tickets for more styling/component splitting and adding the newType
