### ISSUE TITLE
CORS error on front-end

### ISSUE THREAD

**Issue by JonathanLorimer** [Benjmhart/haskql#3]
TBD

**Comment by Benjmhart** [comment]
this is resolved by the following:

http://hackage.haskell.org/package/wai-cors-0.2.6#readme
https://stackoverflow.com/questions/15774833/allowing-cross-origin-requests-in-yesod
https://stackoverflow.com/questions/41399055/haskell-yesod-cors-problems-with-browsers-options-requests-when-doing-post-req

if we add methods with OPTIONS requests, there is some documentation that the middleware may break.

the implementation of the above links can be found in 
<server>/application.hs line 35, line 73

side note: the logWare middleware appears to serve the same purpose as morgan in express 
https://github.com/expressjs/morgan
