### ISSUE TITLE
Implement GraphQL on server + front end

### ISSUE THREAD

**Issue by Benjmhart** [Benjmhart/haskql#4]
TBD

**Comment by Benjmhart** [comment]
current: we are now returning an anon query

Requirements:

1. parse queries (and eventually mutations)
2. get a query for stock on the server.
3. follow through with GQL client on front end

docs for GQL-api haskell :    https://haskell-graphql-api.readthedocs.io/en/latest/tutorial/Introduction.html#running-queries

**Comment by Benjmhart** [comment]
CURL example:

curl -v -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{ greeting(who: \"oscar\") }'    http://localhost:3000/helloGraph

**Comment by Benjmhart** [comment]
note: current handler does not use the body  - but a hardcoded value.

**Comment by JonathanLorimer** [comment]
Was having issues with the above curl, I think the issue is the body. This one works for me

```
curl \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{ "query": "{ me { name } }" }' \
	http://localhost:3000/hellograph
```

**Comment by JonathanLorimer** [comment]
I think we need are going to start with queries before mutations. We need to implement a couple things ourselves:
- Implement parser to get query type from request body
- Implement ADT to represent our query types
- Implement hashmap or function to pattern match on query types and fire resolver
- Implement function to encode resolver response as GraphQL formatted JSON response

I am not sure how much of this our GraphQL library handles for us, but we could implement this ourselves.

**Comment by JonathanLorimer** [comment]
This is a GraphQL parser that generates an AST from the request:
https://github.com/jdnavarro/graphql-haskell

**Comment by JonathanLorimer** [comment]
Interesting reference material:
https://chadaustin.me/2016/02/dropbox-hack-week-graphql-server-in-haskell/

**Comment by Benjmhart** [comment]
the following curl is now fully supported server side

curl \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{ "query": "{ hello { greeting(who: \"Oscar\") } }" }' \

**Comment by Benjmhart** [comment]
gonna close this for now - I think graphQL in haskell is a bigger mountain than we can climb with this project.
